### ISSUE TITLE
tvOS 13.3 Device Support

### ISSUE THREAD

**Issue by haydenjamiesonUIC** [filsv/TVOSDeviceSupport#2]
Is it possible to provide tvOS 13.3 device support files? 

We are experiencing an issue with 1 of our apps specifically on 13.3 and would like to test it more

TIA

**Comment by filsv** [comment]
@haydenjamiesonUIC You can download it [here](https://github.com/filsv/TVOSDeviceSupport/raw/master/13.3.zip).
