### ISSUE TITLE
15.5

### ISSUE THREAD

**Issue by gedw99** [filsv/tvOSDeviceSupport#4]
please add 15.5 tvOS

**Comment by filsv** [comment]
@gedw99 Please try to use 15.6 ([Download](https://github.com/filsv/TVOSDeviceSupport/raw/master/15.6.zip)) Instead or try to rename 15.4 ([Download](https://github.com/filsv/TVOSDeviceSupport/raw/master/15.4.zip)) to 15.5 (should help.)
