### ISSUE TITLE
Request for TvOS 16.2

### ISSUE THREAD

**Issue by jastisatya** [filsv/TVOSDeviceSupport#6]
please provide TvOS 16.2 device configuration files

**Comment by filsv** [comment]
@jastisatya Please try to use 16.4 Instead, and let me know if it helped - [16.4 Download Link](https://github.com/filsv/TVOSDeviceSupport/raw/master/16.4.zip) or try to use [16.1](https://github.com/filsv/TVOSDeviceSupport/raw/master/16.1.zip) (simply rename folder from 16.1 to 16.2).
