### ISSUE TITLE
17.0 ?

### ISSUE THREAD

**Issue by tsra0ne** [filsv/TVOSDeviceSupport#8]
@filsv can you please upload tvOS 17 device support files...

**Comment by filsv** [comment]
@tsra0ne There is no tvOS 17 support files, can you please try to use this command instead and let me know if it's worked for you?

`defaults write com.apple.dt.Xcode DVTEnableCoreDevice enabled`
<img width="863" alt="Screenshot 2024-12-10 at 10 54 18" src="https://github.com/user-attachments/assets/960d492a-7b97-44a3-9490-ade461690633">
([From my iOS Support Files repo](https://github.com/filsv/iOSDeviceSupport))
